// <auto-generated />
using System;
using Lottotry.WebApi.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lottotry.WebApi.Migrations
{
    [DbContext(typeof(LottotryDbContext))]
    [Migration("20211107204011_Add_Table_LottoNumbers")]
    partial class Add_Table_LottoNumbers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lottotry.WebApi.Domain.BC49.BC49", b =>
                {
                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Number3")
                        .HasColumnType("int");

                    b.Property<int>("Number4")
                        .HasColumnType("int");

                    b.Property<int>("Number5")
                        .HasColumnType("int");

                    b.Property<int>("Number6")
                        .HasColumnType("int");

                    b.HasKey("DrawNumber");

                    b.ToTable("BC49");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.Lotto649.Lotto649", b =>
                {
                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Number3")
                        .HasColumnType("int");

                    b.Property<int>("Number4")
                        .HasColumnType("int");

                    b.Property<int>("Number5")
                        .HasColumnType("int");

                    b.Property<int>("Number6")
                        .HasColumnType("int");

                    b.HasKey("DrawNumber");

                    b.ToTable("Lotto649");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.LottoMax.LottoMax", b =>
                {
                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Number3")
                        .HasColumnType("int");

                    b.Property<int>("Number4")
                        .HasColumnType("int");

                    b.Property<int>("Number5")
                        .HasColumnType("int");

                    b.Property<int>("Number6")
                        .HasColumnType("int");

                    b.Property<int>("Number7")
                        .HasColumnType("int");

                    b.HasKey("DrawNumber");

                    b.ToTable("LottoMax");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.LottoNumbers.LottoNumbers", b =>
                {
                    b.Property<int>("LottoName")
                        .HasColumnType("int");

                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBonusNumber")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHit")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("NumberRange")
                        .HasColumnType("int");

                    b.Property<int>("NumberofDrawsWhenHit")
                        .HasColumnType("int");

                    b.HasKey("LottoName", "DrawNumber");

                    b.ToTable("LottoNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
