// <auto-generated />
using System;
using Lottotry.WebApi.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lottotry.WebApi.Migrations
{
    [DbContext(typeof(LottotryDbContext))]
    [Migration("20250515200850_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lottotry.WebApi.Domain.BC49.BC49", b =>
                {
                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Number3")
                        .HasColumnType("int");

                    b.Property<int>("Number4")
                        .HasColumnType("int");

                    b.Property<int>("Number5")
                        .HasColumnType("int");

                    b.Property<int>("Number6")
                        .HasColumnType("int");

                    b.HasKey("DrawNumber");

                    b.ToTable("BC49");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.DailyGrand.DailyGrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Number3")
                        .HasColumnType("int");

                    b.Property<int>("Number4")
                        .HasColumnType("int");

                    b.Property<int>("Number5")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyGrand");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.DailyGrand_GrandNumber.DailyGrand_GrandNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("GrandNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyGrand_GrandNumber");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.Lotto649.Lotto649", b =>
                {
                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Number3")
                        .HasColumnType("int");

                    b.Property<int>("Number4")
                        .HasColumnType("int");

                    b.Property<int>("Number5")
                        .HasColumnType("int");

                    b.Property<int>("Number6")
                        .HasColumnType("int");

                    b.HasKey("DrawNumber");

                    b.ToTable("Lotto649");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.LottoMax.LottoMax", b =>
                {
                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Number3")
                        .HasColumnType("int");

                    b.Property<int>("Number4")
                        .HasColumnType("int");

                    b.Property<int>("Number5")
                        .HasColumnType("int");

                    b.Property<int>("Number6")
                        .HasColumnType("int");

                    b.Property<int>("Number7")
                        .HasColumnType("int");

                    b.HasKey("DrawNumber");

                    b.ToTable("LottoMax");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.LottoNumbers.LottoNumbers", b =>
                {
                    b.Property<int>("LottoName")
                        .HasColumnType("int");

                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBonusNumber")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHit")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("NumberRange")
                        .HasColumnType("int");

                    b.Property<int>("NumberofDrawsWhenHit")
                        .HasColumnType("int");

                    b.HasKey("LottoName", "DrawNumber");

                    b.ToTable("LottoNumbers");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.LottoTypes.LottoType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("LottoName")
                        .HasColumnType("int");

                    b.Property<int>("NumberRange")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LottoTypes");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.Numbers.Number", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<bool>("IsBonusNumber")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHit")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LottoTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LottoTypeId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberofDrawsWhenHit")
                        .HasColumnType("int");

                    b.Property<int>("Probability")
                        .HasColumnType("int");

                    b.Property<int>("TotalHits")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LottoTypeId");

                    b.HasIndex("LottoTypeId1");

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.Numbers.Number", b =>
                {
                    b.HasOne("Lottotry.WebApi.Domain.LottoTypes.LottoType", null)
                        .WithMany()
                        .HasForeignKey("LottoTypeId");

                    b.HasOne("Lottotry.WebApi.Domain.LottoTypes.LottoType", "LottoType")
                        .WithMany("Numbers")
                        .HasForeignKey("LottoTypeId1");

                    b.Navigation("LottoType");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.LottoTypes.LottoType", b =>
                {
                    b.Navigation("Numbers");
                });
#pragma warning restore 612, 618
        }
    }
}
