// <auto-generated />
using System;
using Lottotry.WebApi.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lottotry.WebApi.Migrations
{
    [DbContext(typeof(LottotryDbContext))]
    [Migration("20250417180531_database uniqueness constraint")]
    partial class databaseuniquenessconstraint
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lottotry.WebApi.Domain.BC49.BC49", b =>
                {
                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Number3")
                        .HasColumnType("int");

                    b.Property<int>("Number4")
                        .HasColumnType("int");

                    b.Property<int>("Number5")
                        .HasColumnType("int");

                    b.Property<int>("Number6")
                        .HasColumnType("int");

                    b.HasKey("DrawNumber");

                    b.ToTable("BC49");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.DailyGrand.DailyGrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Number3")
                        .HasColumnType("int");

                    b.Property<int>("Number4")
                        .HasColumnType("int");

                    b.Property<int>("Number5")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyGrand");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.DailyGrand_GrandNumber.DailyGrand_GrandNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("GrandNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyGrand_GrandNumber");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.Emails.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.Lotto649.Lotto649", b =>
                {
                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Number3")
                        .HasColumnType("int");

                    b.Property<int>("Number4")
                        .HasColumnType("int");

                    b.Property<int>("Number5")
                        .HasColumnType("int");

                    b.Property<int>("Number6")
                        .HasColumnType("int");

                    b.HasKey("DrawNumber");

                    b.ToTable("Lotto649");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.LottoMax.LottoMax", b =>
                {
                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Number3")
                        .HasColumnType("int");

                    b.Property<int>("Number4")
                        .HasColumnType("int");

                    b.Property<int>("Number5")
                        .HasColumnType("int");

                    b.Property<int>("Number6")
                        .HasColumnType("int");

                    b.Property<int>("Number7")
                        .HasColumnType("int");

                    b.HasKey("DrawNumber");

                    b.ToTable("LottoMax");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.LottoNumbers.LottoNumbers", b =>
                {
                    b.Property<int>("LottoName")
                        .HasColumnType("int");

                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBonusNumber")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHit")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("NumberRange")
                        .HasColumnType("int");

                    b.Property<int>("NumberofDrawsWhenHit")
                        .HasColumnType("int");

                    b.HasKey("LottoName", "DrawNumber");

                    b.ToTable("LottoNumbers");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.LottoTypes.LottoType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("LottoName")
                        .HasColumnType("int");

                    b.Property<int>("NumberRange")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LottoTypes");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.Numbers.Number", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<bool>("IsBonusNumber")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHit")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LottoTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberofDrawsWhenHit")
                        .HasColumnType("int");

                    b.Property<int>("Probability")
                        .HasColumnType("int");

                    b.Property<int>("TotalHits")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LottoTypeId");

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.Numbers.Number", b =>
                {
                    b.HasOne("Lottotry.WebApi.Domain.LottoTypes.LottoType", "LottoType")
                        .WithMany("Numbers")
                        .HasForeignKey("LottoTypeId");

                    b.Navigation("LottoType");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.Users.User", b =>
                {
                    b.HasOne("Lottotry.WebApi.Domain.Emails.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("Lottotry.WebApi.Domain.LottoTypes.LottoType", b =>
                {
                    b.Navigation("Numbers");
                });
#pragma warning restore 612, 618
        }
    }
}
